apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-workspace-test-1
  namespace: agora-p04-test
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 256Mi
