apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onecli-app-data
  namespace: agora-onecli-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
